id: I5CFD8C44
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:12:30+00:00'
last_modified: '2022-06-09T06:48:07.385624+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3JT13623
  title: ལེགས་བཤད་གསེར་གྱི་ཐུར་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AFFB:
      image_group_id: I3JT13629
      title: Volume 1 of legs bshad gser gyi thur ma/
      total_pages: 26
      order: 1
      base_file: AFFB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
