id: I5CFD8C44
legacy_id: P007867
ocr_import_info:
  bdrc_scan_id: W3JT13623
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T01:12:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:06:56.101000+00:00'
last_modified: 2022-09-04 01:07:00.909360
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3JT13623
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3JT13623
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལེགས་བཤད་གསེར་གྱི་ཐུར་མ།
  author: ཞབས་དཀར་བ་ཚོགས་དྲུག་རང་གྲོལ།
statistics:
  ocr_word_mean_confidence_index: 0.6123925597909324
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I3JT13629:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3JT13629
      total_pages: 26
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3JT13629.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6123925597909324
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
