id: P007867
initial_creation_type: ocr
source_metadata:
  id: bdr:W3JT13623
  title: ལེགས་བཤད་གསེར་གྱི་ཐུར་མ།
  author: ''
  volumes:
    c451e3a5116241339c798deca1a7a50e:
      image_group_id: I3JT13629
      title: ''
      volume_number: 1
      total_pages: 26
ebook_metadata:
  title: ལེགས་བཤད་གསེར་གྱི་ཐུར་མ།
  author: ''
  sku: P007867
  cover: cover.jpg
  layers:
  - pagination
